stages:

  download:
    cmd: nanoplm data download
      --url ${data_dirs.url}
      -o ${data_dirs.compressed_fasta}
    deps:
      - src/nanoplm/data/downloader.py
    params:
      - data_dirs.url
      - data_dirs.compressed_fasta
    outs:
      - ${data_dirs.compressed_fasta}

  extract:
    cmd: nanoplm data extract
      -i ${data_dirs.compressed_fasta}
      -o ${data_dirs.extracted_fasta}
    deps:
      - src/nanoplm/data/extractor.py
      - ${data_dirs.compressed_fasta}
    params:
      - data_dirs.compressed_fasta
      - data_dirs.extracted_fasta
    outs:
      - ${data_dirs.extracted_fasta}

  shuffle:
    cmd: nanoplm data shuffle
      -i ${data_dirs.extracted_fasta}
      -o ${data_dirs.shuffled_fasta}
      --seed ${data_params.shuffle_seed}
    deps:
      - src/nanoplm/data/shuffler.py
      - ${data_dirs.extracted_fasta}
    params:
      - data_dirs.shuffled_fasta
      - data_params.shuffle_seed
    outs:
      - ${data_dirs.shuffled_fasta}
  
  filter:
    cmd: nanoplm data filter
      -i ${data_dirs.shuffled_fasta}
      -o ${data_dirs.filtered_fasta}
      --min-seq-len ${data_params.min_seq_len}
      --max-seq-len ${data_params.max_seq_len}
      --seqs-num ${data_params.seqs_num}
      --skip-n ${data_params.filter_skip_n}
    deps:
      - src/nanoplm/data/filterer.py
      - ${data_dirs.shuffled_fasta}
    params:
      - data_dirs.shuffled_fasta
      - data_params.min_seq_len
      - data_params.max_seq_len
      - data_params.seqs_num
      - data_params.filter_skip_n
    outs:
      - ${data_dirs.filtered_fasta}
  
  split:
    cmd: nanoplm data split
      -i ${data_dirs.filtered_fasta}
      -o ${data_dirs.splitted_fasta_dir}
      --val-ratio ${data_params.val_ratio}
    deps:
      - src/nanoplm/data/splitor.py
      - ${data_dirs.filtered_fasta}
    params:
      - data_dirs.filtered_fasta
      - data_dirs.splitted_fasta_dir
      - data_params.val_ratio
    outs:
      - ${data_dirs.splitted_fasta_dir}
  
  save_kd_train_dataset:
    cmd: nanoplm data save-kd-dataset
      -i ${data_dirs.splitted_fasta_dir}/train.fasta
      -o ${data_dirs.kd_train_dir}
      --teacher-model ${data_params.teacher_model}
      --max-seq-len ${data_params.max_seq_len}
      --n-files ${data_params.train_shards}
      --batch-size ${data_params.embed_calc_batch_size}
      --device ${data_params.device}
      --skip-n ${data_params.filter_skip_n}
    deps:
      - src/nanoplm/data/dataset.py
      - ${data_dirs.splitted_fasta_dir}/train.fasta
    params:
      - data_dirs.splitted_fasta_dir
      - data_dirs.kd_train_dir
      - data_params.max_seq_len
      - data_params.train_shards
      - data_params.embed_calc_batch_size
      - data_params.filter_skip_n
    outs:
      - ${data_dirs.kd_train_dir}

  save_kd_val_dataset:
    cmd: nanoplm data save-kd-dataset
      -i ${data_dirs.splitted_fasta_dir}/val.fasta
      -o ${data_dirs.kd_val_dir}
      --teacher-model ${data_params.teacher_model}
      --max-seq-len ${data_params.max_seq_len}
      --n-files ${data_params.val_shards}
      --batch-size ${data_params.embed_calc_batch_size}
      --device ${data_params.device}
      --skip-n ${data_params.filter_skip_n}
    deps:
      - src/nanoplm/data/dataset.py
      - ${data_dirs.splitted_fasta_dir}/val.fasta
    params:
      - data_dirs.splitted_fasta_dir
      - data_dirs.kd_val_dir
      - data_params.max_seq_len
      - data_params.val_shards
      - data_params.embed_calc_batch_size
      - data_params.filter_skip_n
    outs:
      - ${data_dirs.kd_val_dir}